### ISSUE TITLE
Auch mehr als eine Domain möglich?

### ISSUE THREAD

**Issue by MiRen76** [alcapone1933/docker-ddns-ipv64#1]
Ich habe nur folgende Frage:
Kann ich über die Variable  -e DOMAIN_IPV64 auch mehrere Domains abfragen? Also ungefähr so  -e "DOMAIN_IPV64=domain1.ipv64.net,domain2.ipv64.net"

**Comment by alcapone1933** [comment]
Aktuell habe ich nur eine Domain eingerichtet.
Wenn bedarf da ist werde ich das anpassen.

**Comment by MiRen76** [comment]
Wäre schon cool mehrere Domains über einen Container zu aktualisieren

**Comment by alcapone1933** [comment]
Du kannst vorerst das über 2 Container laufen lassen

**Comment by lachenmeiers** [comment]
@MiRen76 Lege doch CNAME darauf.

**Comment by alcapone1933** [comment]
Wäre auch eine Lösung

**Comment by alcapone1933** [comment]
@MiRen76 Man kann jetzt auch mehrere Domains abfragen

**Comment by MiRen76** [comment]
Super, vielen Dank
