### ISSUE TITLE
Keine Update der IP wenn Probleme mit SHOUTRRR 

### ISSUE THREAD

**Issue by MajorTomDE** [alcapone1933/docker-ddns-ipv64#10]
Hallo,

mir ist folgendes unschöne Verhalten aufgefallen: Ich verwende SHOUTRRR mit Gotify.

Wenn z.B. nach einem Neustart meines Docker Servers der Container für ddns-ipv64 vor dem Gotify Container startet, erhalte ich folgende Meldung und es findet keinerlei Updates der IPs statt. 

```
2024-12-19 23:07:57  FEHLER !!!  - Die Angaben sind falsch  gesetzt: SHOUTRRR URL
2024-12-19 23:07:57    INFO !!!  - Schaue unter https://containrrr.dev/shoutrrr/ nach dem richtigen URL Format
2024-12-19 23:07:57    INFO !!!  - Stoppen sie den Container und Starten sie den Container mit den richtigen Angaben erneut
```

Die URL ist definitiv korrekt, sprich nach einem Neustart von ddns-ipv64 nachdem der Gotify Dienst läuft, passt alles.

Es wäre wenn Du einbaust, dass das Update der IPs unabhängig von der SHOUTRRR Url bzw. der Fehler anders abgefangen wird, damit trotzdem die IPs aktualisiert werden.

Vielen Dank
Tom

**Comment by alcapone1933** [comment]
Hallo @MajorTomDE,

wenn du vielleicht die Dokumentation gelesen hast, kannst du die Testnachricht überspringen, indem du die Variable `SHOUTRRR_SKIP_TEST=yes` setzt.

Dann startet der Container trotzdem. Es wird zwar keine Nachricht gesendet, wenn der Link falsch ist, aber das Update funktioniert dennoch.

Dass keine Nachricht gesendet wird, kann mehrere Ursachen haben.

Vielleicht teste mal deinen Link über die Konsole:

`docker run --rm -it alcapone1933/shoutrrr send --verbose --url "< Shoutrrr URL >" --message "DOCKER DDNS UPDATER IPV64.NET"`

`docker run --rm -it alcapone1933/shoutrrr send --verbose --url "gotify://domain.de/123456abc/?title=DDNS+IPV64+IP+UPDATE&priority=5" --message "DOCKER DDNS UPDATER IPV64.NET"`


Viele Grüße alcapone1933

**Comment by alcapone1933** [comment]
Schließe es hier
