### ISSUE TITLE
Support ipv6 as well

### ISSUE THREAD

**Issue by matthias-eb** [alcapone1933/docker-ddns-ipv64#3]
The entrypoint script currently only updates the A-Record for the given URL, but not the AAAA-Record for ipv6-Adresses.
As the ipv64.net page uses ipv6 first rather than ipv4 and ipv6 is absolutely necessary for people with a DS-Lite connection, I would be very happy if you could add this.

Deutsche Version:
Das entrypoint skript benutzt updatet derzeit nur die ipv4 Adresse im A-Record, die IPv6 Adresse im AAAA Record wird ignoriert.
Da die ipv64.net Seite Ipv6 in erstelr Linie mit der Rückfallmöglichkeit auf IPv4 benutzt, und Benutzer mit DS-Lite anschluss auf IPv6 Adressen angewiesen sind, wäre ich sehr glücklich, wenn der entsprechende IPv6 Eintrag noch hinzugefügt wird.

**Comment by alcapone1933** [comment]
Ich werde mal die nächten tage schauen , ob ich das hinbekomme auch für ipv6 es einzurichten.
