### ISSUE TITLE
IP wird nicht erkannt und aktualisiert

### ISSUE THREAD

**Issue by Knoddel** [alcapone1933/docker-ddns-ipv64#5]
Ich habe seit heute das Problem das die IP nicht mehr erkannt und aktualisiert wird.
An meinem System wurde nichts verändert. 
Docker Version  20.10.21
Docker Compose Version 2.12.2

Duckdns macht keine Probleme, dort funktioniert noch alles.

![Screenshot 2022-11-10 192344](https://user-images.githubusercontent.com/53978522/201176716-b56cd913-0375-475b-a4b9-f5a399af35f1.jpg)

![Screenshot 2022-11-10 192532](https://user-images.githubusercontent.com/53978522/201176717-3e4e53c6-c8b8-4178-8668-66357410c9c1.jpg)

**Comment by alcapone1933** [comment]
Hast du schon das neue Update dir gepullt

**Comment by alcapone1933** [comment]
Habe eine neue Version , weil es eine Änderung gab mit dem Update output, schau bei 
https://github.com/alcapone1933/docker-ddns-ipv64/issues/4 nach

**Comment by Knoddel** [comment]
Das Image ist vom 08.11 sollte das Aktuelle sein. 
Ich hole mir über Watchtower automatisch immer die neuesten Images.
Kann es sein das ip64.net selbst Probleme hat, den ich komme auch auf die Website nicht mehr drauf.

**Comment by Knoddel** [comment]
Im log habe ich gerade gesehen das ab und zu doch eine Abfrage durchgeht

**Comment by alcapone1933** [comment]
Also im habe im Docker Container die Funktion das er erst ein Ping an die Webseite schickt und wenn die nicht erreichbar ist macht er nicht weiter , weil es ja kann sinn macht etwas wo hinzuschicken was nicht da ist.

Ich hatte hatte gestern ein ähnliches Problem, ich konnte die Webseite nicht aufrufen.
Vieleicht ist das Anbieter mässig so, weil mein Anbieter in Deutschland Probleme hatte bezüglich des Internets.
Mein DDNS Updater war nicht die Ursache dessen , weil ich es ja selber sehr oft teste, an mehreren Stantorten.
