### ISSUE TITLE
Die Angaben sind falsch  gesetzt: DOMAIN oder DOMAIN KEY

### ISSUE THREAD

**Issue by MajorTomDE** [alcapone1933/docker-ddns-ipv64#6]
Hey,

in meinem Docker Log erhalte ich den Fehler **"Die Angaben sind falsch  gesetzt: DOMAIN oder DOMAIN KEY"**

Ich komme nicht drauf, was ich falsch mache  - auch weil die IPs korrekt in IPV64 gesetzt werden.

Variablen habe ich wie folgt hinterlegt:
```
DOMAIN_IPV64	meinedomain1.ipv64.de,meinedomain2.vpn64.de
DOMAIN_KEY	123456789101111
```

Als DOMAIN_KEY verwende ich den DynDNS Update Hash.

Weißt Du was der Fehler sein könnte?

```
================================ START DDNS UPDATER IPV64.NET ================================
2022-12-02 11:29:23  DOMAIN      - Sie haben eine DOMAIN gesetzt
2022-12-02 11:29:23  DOMAIN      - Deine DOMAIN meinedomain1.ipv64.de
2022-12-02 11:29:23  DOMAIN      - Deine DOMAIN meinedomain2.vpn64.de
2022-12-02 11:29:23  DOMAIN KEY  - Sie haben einen DOMAIN Key gesetzt
2022-12-02 11:29:23  FEHLER !!!  - Die Angaben sind falsch  gesetzt: DOMAIN oder DOMAIN KEY
```

Viele Grüße
Thomas

**Comment by alcapone1933** [comment]
Hallo @MajorTomDE ich teste den Docker Container fast jeden tag.
Aktuell läuft alles bei mir und habe es gerade noch mal getestet.
Hast du dir das Aktuelle Image heruntergeladen ? 
Bis version v0.0.4 wahr ein kleiner fehler drin.
 
Mir ist aufgefallen wenn ein CNAME Record gesetzt ist funktioniert das update nicht. bei meinem Container.

Versuch mal den befehl in einer Shell abzusetzten und schaub ob es geklappt hat ansonsten, wende dich an ipv64.net

```bash
curl -4sSL "https://ipv64.net/update.php?key=    &domain=   "
```

Ich bekomme diesen Fehler als ausgabe wenn ein CNAME Record gesetzt ist.
```json
{"status":"403 Forbidden","ip":{"ipv4":"1.1.1.1"},"info":"CNAME is set."}
```

**Comment by MajorTomDE** [comment]
Hallo,

ich habe gerade den curl Befehl geteset. Es funktioniert alles:

`{"status":"success","ip":{"ipv4":"123.456.78.9"},"info":"nochg"}`

Ich denke ich habe noch einen Anhaltspunkt gefunden. Es könnte am "DynDNS Update Limit / 24h" liegen.
Mir ist der Fehler aufgefallen, wenn das Limit von 48 erreicht war.

Ich werde mal mit den Cron Schedules spielen. Jetzt muss ich mal doof fragen:
Ist **CRON_TIME_DIG** oder **CRON_TIME** für das Update auf ipv64 zuständig?

Schau: Gestern Abend kam der Fehler, heute Morgen nicht.

```
================================ START DDNS UPDATER IPV64.NET ================================
2022-12-03 22:56:43  DOMAIN      - Sie haben eine DOMAIN gesetzt
2022-12-03 22:56:43  DOMAIN      - Deine DOMAIN meinedomain1.ipv64.de
2022-12-03 22:56:43  DOMAIN      - Deine DOMAIN mainedomain2.vpn64.de
2022-12-03 22:56:43  DOMAIN KEY  - Sie haben einen DOMAIN Key gesetzt
2022-12-03 22:56:43  FEHLER !!!  - Die Angaben sind falsch  gesetzt: DOMAIN oder DOMAIN KEY
================================ START DDNS UPDATER IPV64.NET ================================
2022-12-04 09:38:06  DOMAIN      - Sie haben eine DOMAIN gesetzt
2022-12-04 09:38:06  DOMAIN      - Deine DOMAIN meinedomain1.ipv64.de
2022-12-04 09:38:06  DOMAIN      - Deine DOMAIN meinedomain2.vpn64.de
2022-12-04 09:38:06  DOMAIN KEY  - Sie haben einen DOMAIN Key gesetzt
2022-12-04 09:38:06  CHECK       - Die Angaben sind richtig gesetzt: DOMAIN und DOMAIN KEY
2022-12-04 09:38:06  IP CHECK    - Deine DOMAIN meinedomain1.ipv64.de HAT DIE IP=123.456.78.9
2022-12-04 09:38:06  IP CHECK    - Deine DOMAIN meinedomain2.vpn64.de HAT DIE IP=123.456.78.9
```

**Comment by alcapone1933** [comment]
Mein Tool checkt nur am start des Containers ob die Angaben richtig sind mit eine Anfrage .
Ansonsten Schicke ich wie Beschrieben:
Bei einer Änderung der ipv4 Adresse am Standort wird die neue ipv4 Adresse als A-Record an ipv64.net geschickt.

Die Variable CRON_TIME_DIG  ist für den Namenserver anfrage.
Die Variable CRON_TIME     ist für das Script das die aktuelle ip prüft zustädig.

Es hängt natürlich davon ab wie oft deine ip sich ändert oder du den Container Neustartest.

**Comment by MajorTomDE** [comment]
Hey @alcapone1933 

Das Problem "Die Angaben sind falsch  gesetzt: DOMAIN oder DOMAIN KEY" existiert immer noch, allerdings wirft jetzt der curl-Befehl den korrekten Fehler aus:

`{"status":"403 Forbidden","info":"Updateintervall overcommited"}`

Anscheinend hat Dennis am Dienst was geändert.

Ich habe heute viel mit Docker gespielt und durch diverse Neustarts die in der Free-Version 48 von 48 Updates erreicht.

So wie der Fehler aktuell ins Logfile geschrieben wird passt daher nicht, da Domains bzw Domain Key korrekt gesetzt sind.
In meinem Fall sind keine Updates wegen der Free-Einschränkung möglich.

Wäre super, wenn Du den Fehler korrekt behandelts und im Logfile ausgibst. Aktuell startet sich der Dienst/Container alle ca 10 Sekunden neu und schreibt den Fehler (Die Angaben sind falsch gesetzt...) ins Logfile. Das heißt das Logfile läuft voll, bis wieder Updates möglich sind.

Viele Grüße
Tom

**Comment by alcapone1933** [comment]
Ich habe es geändert ,das er es in der Log anzeigt ob das Update Limit überschritten ist.
Mein Docker Container fragt bei ipv64 ja nur die angaben bei starten. Und Maximal bei einen Ip Wechel.
Bei Normal gebrauch sind das 3-5 anfragen pro Tag.
Wenn du mit Docker sachen ausprobiert ,dann must du selbst schauen das deine Update Limit nicht überschrieten werden oder dir ein Account zulegen wo du mehr anfragen stellen kannst.
Bitte wende dich da an Ipv64 wenn du mehr möchtest.
