### ISSUE TITLE
DOMAIN_KEY für mehrere Domänen - Liste von Domain Keys erlauben anstelle von Account Update Token

### ISSUE THREAD

**Issue by Gulpman** [alcapone1933/docker-ddns-ipv64#7]
Hallo,
ich habe einen Feature Request zu Deinem Container.

In der Konfiguration werden die Parameter DOMAIN_IPV64 und DOMAIN_KEY unterstützt.

- DOMAIN_IPV64 erlaubt eine Liste von Domänen anzugeben.
- DOMAIN_KEY erlaubt anscheinend nur EINEN Parameter.

Um also eine Liste von Domänen ans Laufen zu bekommen, muss ich unter DOMAIN_KEY nicht die jeweiligen Domain Update Tokens angeben, sondern das Account Update Token, dann klappt es auch.

Es wäre schön, wenn der Parameter DOMAIN_KEY ebenfalls eine Liste von Domain Update Tokens erlauben würde, so dass ich hier nicht das Account Update Token übermitteln muss. 

Beste Grüße
Sascha

**Comment by alcapone1933** [comment]
Du kannst ja mehrer docker Container Ausetzten oder einen CNAME erstellen für deine Domains.
