### ISSUE TITLE
Probleme beim erreichen des externen DNS-Server

### ISSUE THREAD

**Issue by Haecky** [alcapone1933/docker-ddns-ipv64#8]
Guten Tag,

Ich benutze seit kurzem den "docker-ddns-ipv64" wie ich gerade feststelle habe ich schon über 170 Updates damit am heutigen Tag verschickt.

Nach Studium der Logfiles bin ich zu der Annahme gekommen, dass es daran liegt das kein anderer DNS-Server außer meinem PiHole in meinem Netzwerk erlaubt ist. (Port 53 nach draußen ist zu, damit sich keiner um meine Filter rum mogeln kann)

Ist es möglich diese Prüfung abzuschalten, oder den DNS in Skript zu verändern?

Auszug aus dem Log:

2023-02-20 14:15:00  KEIN UPDATE - Aktuelle IP=99.888.77.66
======================================================================================
2023-02-20 14:15:09  UPDATE !!! ...
2023-02-20 14:15:09  UPDATE !!!  - NACHEINTRAG DIE IP WIRD NOCH EINMAL GESETZT
2023-02-20 14:15:09  UPDATE !!!  - Update IP=99.888.77.66 - Alte-IP=99.888.77.66
2023-02-20 14:15:09  UPDATE !!!  - UPDATE IP=99.888.77.66 WURDE AN IPV64.NET GESENDET
2023-02-20 14:15:09  NACHEINTRAG - DOMAIN HAT DEN A-RECORD=;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; no servers could be reached
======================================================================================
2023-02-20 14:20:00  KEIN UPDATE - Aktuelle IP=99.888.77.66
======================================================================================
2023-02-20 14:20:07  UPDATE !!! ...
2023-02-20 14:20:07  UPDATE !!!  - NACHEINTRAG DIE IP WIRD NOCH EINMAL GESETZT
2023-02-20 14:20:07  UPDATE !!!  - Update IP=99.888.77.66 - Alte-IP=99.888.77.66
2023-02-20 14:20:07  UPDATE !!!  - UPDATE IP=99.888.77.66 WURDE AN IPV64.NET GESENDET
2023-02-20 14:20:21  IP CHECK    - Deine DOMAIN xxxx.lan64.de HAT DIE IP=;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; no servers could be reached
======================================================================================
2023-02-20 14:20:07  NACHEINTRAG - DOMAIN HAT DEN A-RECORD=;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; communications error to 159.69.110.93#53: host unreachable
;; no servers could be reached
======================================================================================

**Comment by alcapone1933** [comment]
Dast du DSL-Lite oder so. WIie sieht deine docker compose aus.
Kommt darauf an was du updaten willst wir z.b domain oder subdomain , weil bei der subdomain musst du auch Präfix =Yes aktivieren:
Der Domain Token muss auch zur Domain passen.
Versuch man den dns server in deinem Container oder in der compose zu ändern vieleicht ändert das was.

```
# docker
--dns=1.1.1.1 --dns=1.0.0.1
# compose
    dns:
      - "1.0.0.1"
      - "1.1.1.1"
```

**Comment by Haecky** [comment]
Nein, ich habe kein DSL-Lite oder so auch meine IP wird korrekt übertragen.
Nur die später folgende DNS abfrage bei bei "ns1.ipv64.net" ist wegen gesperrtem Port 53 nicht möglich und von mir auch erwünscht.

docker-compose.yml

version: "3.9"
services:
  ddns-ipv64:
    # build:
      # dockerfile: ./Dockerfile
    image: alcapone1933/ddns-ipv64:latest
    # image: alcapone1933/ddns-ipv64:v0.1.1
    container_name: ddns-ipv64
    restart: always
   # volumes:
    #  - ./data:/data
    environment:
      - "TZ=Europe/Berlin"
      - "CRON_TIME=*/5 * * * *"
      - "CRON_TIME_DIG=*/10 * * * *"
      - "DOMAIN_IPV64=xxxx.lan64.de"
      # - "DOMAIN_IPV64=deine-domain.ipv64.net,deine-domain.ipv64.de"
      # - "DOMAIN_PRAEFIX_YES=yes"
      #  ^z   ^o Hier bitte nur ein DOMAIN PRAEFIX (subdomain) eintragen (ersetzen)  ^z   ^o
      # - "DOMAIN_PRAEFIX=ddns"
      - "DOMAIN_KEY=fsfscdscdvdxcdsfvscssfcsdsdcsdfv"
      # - "SHOUTRRR_URL="
# volumes:
  # data:
    # name: ddns-ipv64_data

**Comment by alcapone1933** [comment]
Es sind ja Persöhliche Einstellungen von dir dein Port zu sperren.
Da wäre mein Projekt das falsche für dein Anwendungsfall.

**Comment by Haecky** [comment]
Darf ich fragen für was die Abfrage gebraucht wird, ich hab die bei keinem anderen Dyndnsupdater?

**Comment by alcapone1933** [comment]
Um abzufragen ob die Domain auch die richtige ip Adresse hat.

**Comment by Haecky** [comment]
Ist es da nicht besser die Adresse selbst anzupingen?

**Comment by alcapone1933** [comment]
Du kannst es ja für dich selbst anpassen. 
Ich mach hier das issues zu.
